spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    path: /swagger-ui